# Generated by Django 2.2.4 on 2019-08-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcela',
            old_name='finca',
            new_name='finca_origen',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='parcela',
            new_name='parcela_origen',
        ),
    ]
