# Generated by Django 2.2.4 on 2019-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25, unique=True)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('permiso', models.CharField(max_length=1)),
            ],
        ),
    ]
